load("@buck2-haskell//:oneshot_linkables.bzl", "haskell_oneshot_linkables")
load("@buck2-haskell//:worker_config.bzl", "oneshot_linker_enabled")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "script_template_processor",
    main = "script_template_processor.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "generate_target_metadata",
    main = "generate_target_metadata.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "generate_toolchain_lib_metadata",
    main = "generate_toolchain_lib_metadata.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "ghc_wrapper",
    main = "ghc_wrapper.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "ghc_pkg_registerer",
    main = "ghc_pkg_registerer.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "compute_exposed_packages",
    main = "compute_exposed_packages.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "build_oneshot_linkables",
    main = "build_oneshot_linkables.py",
    visibility = ["PUBLIC"],
)

haskell_oneshot_linkables(
    name = "oneshot_linkables",
    linker = oneshot_linker_enabled(),
    src = "oneshot_linkables/Buck2Haskell/OneshotLinkables.hs",
    visibility = ["PUBLIC"],
)
